name: tayamer
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  http: ^1.3.0
  shared_preferences: ^2.5.3
  provider: ^6.1.4
  image_picker: ^1.0.4
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  intl: ^0.20.2
  share_plus: ^10.1.4
  flutter_local_notifications: ^19.0.0
  confetti: ^0.8.0
  flutter_pdfview: ^1.3.2
  firebase_core: ^2.27.1
  firebase_messaging:
  mobile_scanner: ^3.5.7 # Yeni QR tarayıcı paketi
  font_awesome_flutter:
  permission_handler: ^11.3.0
  google_ml_kit: ^0.16.3
  device_info_plus: ^9.1.2
  credit_card_scanner: ^1.0.5
  version: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
 